### ISSUE TITLE
radab refactoring

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/random.cdisc.data#154]
# Original message

Thank you @legrasv and @shajoezhu!

I briefly review the first ADAB data. There are some notes for the next refactor version.

1. To simplify, we only need to keep `PARCAT1 == Drug X Antibody`, which means only Drug X have drug antibody data.
2. Usually, RELTMU = day
3. In the first version, only baseline ADA records exsit `VISIT == Day 1`, will need to add post-baseline records for the pts in A and C treatment for the ADA TLGs.
4. The baseline ADA records also required for the patient in B placebo group. Post-baseline records are not needed.
5. After adding post-baseline records, more PARAM/PARAMCD will be needed.
6. **ADABLFL** is baseline ADA evaluable patient flag, **ADAPBLFL** is Post-Baseline ADA Evaluable patient flag, once we add post-baseline records, we can assume all ADABLFL = Y and all ADAPBLFL[where ACTARM  = A: Drug X or C: Combination] = Y
7. **ABLFL** is baseline record flag, for the records with NRELTM1 = 0, ABLFL = Y

Thanks,
Qi

_Originally posted by @qiliu1013 in https://github.com/insightsengineering/random.cdisc.data/issues/143#issuecomment-1135147578_

**Comment by khatril** [comment]
Looking into this issue, a few things I've noticed @qiliu1013 :
1. Do you mean that `PARCAT1 = Drug X Antibody where ARM = A: Drug X, else set to NA`? What should PARCAT1 be set to if ARM is Placebo or Combination?

**Comment by qiliu1013** [comment]
Hi @khatril, sorry I missed your question earlier. Please set PARCAT1 = Drug X Antibody for all the ARMs. For ARM = A: Drug X and Combination, there will be both baseline/post-baseline ADA records, for ARM = Placebo, there will be only baseline ADA records.

Thanks,
Qi
