### ISSUE TITLE
Add metabolites in ADPP

### ISSUE THREAD

**Issue by legrasv** [insightsengineering/random.cdisc.data#155]
We would need to generate other random data for PPCAT = "Metabolite Drug X" and "Metabolite Drug Y"

At the end, please check that the variable AVAL for **Plasma Drug X**  and **Metabolite Drug X** are different.

**Comment by 6iris6** [comment]
Hi @legrasv, Do you know if a patient could have both "Plasma Drug X" and "Metabolite Drug X"? In other words, what's the relationship between ACTARM and PPCAT?

**Comment by legrasv** [comment]
@6iris6 That is a good question actually.
A single patient can have "Plasma Drug X" and "Metabolite Drug X" but should have a unique ACTARM because.

Ex:
PatientID = "ID-6", ACTARM = "ARM A : Drug X", PPCAT = "Plasma Drug X", 
PatientID = "ID-6", ACTARM = "ARM A : Drug X", PPCAT = "Metabolite Drug X"

ACTARM corresponds to the cohort, so a single patient can only be in one cohort
