### ISSUE TITLE
ADPP : create 6 cohorts

### ISSUE THREAD

**Issue by legrasv** [insightsengineering/random.cdisc.data#156]
# TODO

1. Create a fake PKARMCD arm variable, divide the current 2 arms, into 10 groups: drug A ... J 

for PKPG01 only, first step is to do

ADPP <- ADPP %>% mutate(ARMCD = PKARMCD), so we can use 10 cohorts rather than 2.

**Comment by khatril** [comment]
@Melkiades @legrasv Do we still need this enhancement if #244 is now resolved with Davide's suggestion?
