### ISSUE TITLE
Add count endpoint to adtte

### ISSUE THREAD

**Issue by brandondbutcher** [insightsengineering/random.cdisc.data#161]
### Feature description

Motivation

This is part of adding the new template RATET01, see https://github.com/insightsengineering/tern/issues/319

To-Do

- [ ] Add additional rows to `adtte` in `random.cdisc.data` package for count AVAL
- [ ] Add an additional column to `adtte` in `random.cdisc.data` package for a new variable, `lgTMATRSK`, for the corresponding follow up time variable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by brandondbutcher** [comment]
FYI @abhiseabhi01 @shajoezhu

**Comment by shajoezhu** [comment]
Thanks a lot @brandondbutcher . with the item 

" Create an example dataset in tern of a count endpoint with a time at risk variable"

just wondering do we still need it? can we just load adtte from the cached data, and preprocess and pipe it into the function?

Is it going to be a lot preprocessing code? if so, yes, we may consider to create this example data set, alternatively if we can standardize the input data, we should also consider to write h_ helper functions in tern. Thanks!

**Comment by brandondbutcher** [comment]
Ah, yes I meant to delete that bullet point.
