### ISSUE TITLE
refactor the ADAB data

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/random.cdisc.data#170]
>  I saw VISIT = DAY 2 was in the ADAB data. However, PARAM only has values "Antibody titer units" and "ADA interpreted per sample result". We need to refactor the ADAB to add more parameter such as "Treatment induced ADA (Y/N)", "Treatment enhanced ADA (Y/N)", "Time to onset of ADA (Weeks)", "Persistent ADA (Y/N)", "Transient ADA (Y/N)" and "ADA Duration (Weeks)" before design the ADAT02.

see discussion in https://code.roche.com/nest/docs/tlg-catalog/devel/-/issues/146

**Comment by shajoezhu** [comment]
Iris: Hi PK SMEs, do you know how could I find whether a patient has 'an ADA assay' or 'NAb assay' from ADAB? I am working on design doc for ADAT04B. From ADAB.PARAM, I can only find 'ADA interpreted per sample result' and 'Antibody titer units', shall I check other variables or datasets? Thanks!

Qi: Hi @Iris Zhao, we don't have the nab records in the ADAB data for now. PARAM = "NAB interpreted per sample result" and "Anti-RO5541077 Neutralizing Antibody titer" are the nab records. Additionally, to create ADAT04B, we need to refactor the ADAB to add more PARAMs, such as "Post-Baseline Pos/Neg", "NAB Status of a patient", and "Post-Baseline Pos/Neg".

Iris: Thanks Qi! Do you know if we need more ARMs in ADAB as well? We only have 'Drug X ,    Placebo , Combination', but in ADAT04B it will need 'Group 1, Group 2, All drug patients, control group', so I think we need something like 'Drug Y'?

Qi: Drug X is sufficient. In the ADAT04B column, it will be Drug X, Combination, All Drug X patients, Placebo, All patients.
All Drug X patients= Drug X+Combination

**Comment by edelarua** [comment]
Hi @mingyu528 @stevedgthb, 

Could you please provide me with more information on some of the PARAMs I am adding to adab? I would like to confirm how `Post-Baseline Pos/Neg` and `NAB Status of a patient` should be derived, and what the PARAMCD values should be for the NAb PARAMs I am adding (listed in the comment above). Additionally, I do not have a description for `Treatment enhanced ADA (Y/N)` (this is not used for ADAT02 or ADAT04B).

For the ADA PARAMs I added I was using [this table](https://github.com/insightsengineering/random.cdisc.data/issues/143#issuecomment-1121621285) as a reference as well as the descriptions listed in the [ADAT02 design template issue](https://code.roche.com/nest/docs/tlg-catalog/devel/-/issues/146).

Thanks!

**Comment by qiliu1013** [comment]
Hi @edelarua,

Please see the dummy data below. This should include all the PARAM we need for the ADA TLGs. In real data, `NAB Status of a patient` is derived from `Post-Baseline Pos/Neg`. We don't have to have `Post-Baseline Pos/Neg` in the dummy data.

![Screen Shot 2022-07-22 at 11 15 14 AM](https://user-images.githubusercontent.com/24441440/180499846-e432b9e8-5250-413f-8cb5-bdcddaf9745a.png)

`Treatment enhanced ADA (Y/N)` will be used in the ADAL02.

Please let me know if you have any questions.

Thanks!
