### ISSUE TITLE
Add EXDOSFRQ, EXROUTE and EXENDY to ADEX data

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/random.cdisc.data#173]
- [x] EXDOSFRQ, Dosing Frequency per Interval
- [x] EXROUTE, Route of Administration
- [x] EXENDY, Study Day of End of Treatment

For more info, see https://gdsr.roche.com/ui/gdsr-browser-app%23GDSRBrowser#/default/http%3A%2F%2Fgdsr.roche.com%2Fui%2Fws%2Fdata-analysis-ui%23NavigationScheme.DataAnalysis/view/http%3A%2F%2Fgdsr.roche.com%2Fpd-biometrics%2Fadam-ADEXv%23Sponsor-Table.ADEX/gdsr.roche.com

**Comment by malexthorpe** [comment]
Hey @shajoezhu it's simple to add EXDOSFRQ and EXROUTE but to add EXENDY we also need to add other columns like:
VISIT, VISITDY, EXSTDTC, EXENDTC, EXSTDY.
