### ISSUE TITLE
ADEG refactoring with ADY

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/random.cdisc.data#184]
there are data issues in ADEG on ADY, where for same subject ADY is different for same visit at different parameters, for example : ADY for Hart Rate at Visit 1 is 3, but for QRS at Visit 1, ADY is 10.

another example

![image](https://user-images.githubusercontent.com/3692541/181701702-8249d345-a3bb-41c9-8fe3-36eb43056be7.png)

**Comment by Melkiades** [comment]
I have a workaround for this that I mentioned in the comments but I think, as this is not yet a blocker, that is better to fix ADSL first in the next dev sprint. Many dates should be also related to AVISIT while they are often not and span larger windows.
