### ISSUE TITLE
Refactor ADPC dataset to include urine data

### ISSUE THREAD

**Issue by ayogasekaram** [insightsengineering/random.cdisc.data#207]
PKCL02 listing requires urine drug concentration observations to create the template. PCTPT values for these observations should also be an interval (ex. 0-4H).  A `ASMED` or `PCSPEC` column may need to be added to differentiate between "PLASMA" and "URINE" values.

**Comment by legrasv** [comment]
PCSPEC = "URINE", PARAM = "Urine Plasma Drug X" or "Urine Plasma Drug Y" PCTPT = "0-4H" "4-8H" "8-12H" "12-24H" "24-48H"

In reality, the drug does not usually go in the urine in the first 4 hours, so it's usually BLQ 0-4H, then it's quite high around 1500 in average AT 4-8H, then it goes down 300 at 8-12H and almost nothing later, it's like the PK curve but the peak is at 4-8H
AVAL should start at 0 at 0

**Comment by shajoezhu** [comment]
closed by https://github.com/insightsengineering/random.cdisc.data/pull/211
