### ISSUE TITLE
refactor ADPC and ADAB

### ISSUE THREAD

**Issue by legrasv** [insightsengineering/random.cdisc.data#212]
ADPC
1. refine ADPC so that the visit changes after 7 days (coded in Weeks), and then I could be able to refine ADAB and make it match by usubjid paramcd visit;
2.recode the visits of ADPC: Day 1 2 3.. 6, Day 7, Week 4 Week 8 etc..
to make it match with ADAB which will have Visit = Day 1, Week 4 Week 8 ... 

ADAB
1. VISIT = Day 1 (ISTPT = "Predose"), Week4 (ISTPT="") , Week 8 etc. 
3. adding this ATACHAR column (that contain nothing or molecule A+, B+ etc. randomly assigned)

**Comment by shajoezhu** [comment]
closed in #219
