### ISSUE TITLE
adding PPBSISB to adsub (required by ssrsl01)

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/random.cdisc.data#216]

**Comment by edelarua** [comment]
@shajoezhu the SSRSL01 template ([design here](https://code.roche.com/nest/docs/tlg-catalog/devel/-/issues/141)) has three columns that we don't currently have data for. Columns 4 and 5 - "Subcategory for Question" and "CASA Category" - are not part of ADSUB, they come from another dataset ADCSSRS which we don't currently have. The values for PPBSISB in ADSUB also are derived from this dataset.

Assuming that we do no want to create this dataset for only one template, should we randomly generate the values for the PPBSISB variable instead? And randomly generate the values for the other two columns from within the template (as in the current design)?

Let me know how I should proceed with this!

**Comment by edelarua** [comment]
@shajoezhu any update on this issue?

**Comment by edelarua** [comment]
SSRSL01 will not be added to TLG-C so no updates to `random.cdisc.data` needed.
