### ISSUE TITLE
Refactor ADPC following the new OCEAN Specs

### ISSUE THREAD

**Issue by qiliu1013** [insightsengineering/random.cdisc.data#280]
The new ADPC specs will be applied in the OCEAN studies. We need to update the test ADPC for the new specs.

Adding the following variables in the ADPC.

1. Set AVALCAT1 (Analysis Value Category 1) = AVALC. [This variable impact the PKCT01 and 1/3 imputation rule.] 
2. Set NFRLT (Nom. Rel. Time from Analyte First Dose)  = NRELTM1 [This variable impact the PKCT01 and 1/3 imputation rule.] 
3. Set AFRLT (Act. Rel. Time from Analyte First Dose) = ARELTM1
4. Set NRRLT (Nominal Rel. Time from Ref. Dose) = NRELTM2
5. Set ARRLT (Actual Rel. Time from Ref. Dose) = ARELTM2
6. Add ANL02FL (Analysis Flag 02) == "Y" for all records. This variable needs to be applied in the data preprocessing step in all TLGs.

**Comment by Melkiades** [comment]
what bug?

**Comment by qiliu1013** [comment]
Hi @Melkiades,

We will need to follow the new ADPC specs in OCEAN. Main changes are add dosing records into ADPC and renames certain variables. I will need some time to summarize all the details. Will edit the issue soon.

Thanks,
Qi

> what bug?

**Comment by Melkiades** [comment]
Sorry for pushing and thanks for the specification :)

**Comment by qiliu1013** [comment]
@shajoezhu, the new ADPC specs will be applied in the OCEAN studies only for now. Adding more variables might be more reasonable instead of rename variables. pRED colleagues may still use the original ADPC for NEST TLGs preparation.  What do you think?

**Comment by shajoezhu** [comment]
hi @qiliu1013 , I would suggest to use one standard, and we will have something to refer to in the future. Otherwise we start building technical debt in our package. 

We have different versions and tags, people can use or reference to an older version if they need. 

So I suggest to follow the new standard, and deprecate the old columns. We will make the history updates in the news, what do you think would be the best way to share this info with our PK scientist?

**Comment by qiliu1013** [comment]
Thank you @shajoezhu, I see. I will deprecate the old columns. Both gRED and pRED will follow the new specs eventually. The new specs are the global CDISC standard. This won't impact much on PK scientist but MSA and CPDS in pRED. In the next TLG-c release, it would be great if we could mention the new ADPC specs is applied.
