### ISSUE TITLE
Refactor ADAB

### ISSUE THREAD

**Issue by qiliu1013** [insightsengineering/random.cdisc.data#315]
### What happened?

A bug happened!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
@qiliu1013 Could you add a reproducible example and some indication on how to fix this issue!!
